### ISSUE TITLE
 websocket connection is disconnected after 3 minutes

### ISSUE THREAD

**Issue by bharath-naik** [minhpq331/jitsi-scalable-helm#2]
After repeatedly trying on GKE with three optimized clusters, i was getting the same below error. couldn't figure out for stable connection of rooms.

here is my values_custom.yaml link [https://github.com/minhpq331/jitsi-scalable-helm/issues/1#issue-1073509959](url)

![image](https://user-images.githubusercontent.com/20774548/145722044-4c21116a-255e-4924-83da-9daf31727971.png)

![image](https://user-images.githubusercontent.com/20774548/145721994-035f16eb-a387-4ce8-a0e7-375568340957.png)

I tried the following

1. ENABLE_XMPP_WEBSOCKET=0
2.  changing to latest images
3. ENABLE_SCTP=1 and 
4.  gce load balancer.
@bharath-naik As far as I can see, your pods and your services are working as expected but your ingresses are not. You need to add some specific annotations to get GCE builtin ingresses working. 
Some configurations to make this chart work with GKE and GCE ingress:

Custom-values.yaml (I only list important parts)
```yaml
jvb:
  websocket:
    service:
      annotations: 
        beta.cloud.google.com/backend-config: '{"ports": {"9090":"jvb-websocket-config"}}'

haproxy:
  service:
    annotations: 
      beta.cloud.google.com/backend-config: '{"ports": {"80":"haproxy-config"}}'
  ingress:
    hosts:
      - host: socialhour.vewmet.com
        paths:
          - path: /*  # THIS IS IMPORTANT, note this '*'
            pathType: ImplementationSpecific
```

GCE backend config (kubectl apply this file)
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: haproxy-config
spec:
  timeoutSec: 2100 # timeout connection for haproxy, set your
  connectionDraining:
    drainingTimeoutSec: 2100
  healthCheck:
    checkIntervalSec: 15
    port: 7880
    type: HTTP
    requestPath: /
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: jvb-websocket-config
spec:
  timeoutSec: 2100 # 35 minutes  # timeout connection for haproxy, set your
  connectionDraining:
    drainingTimeoutSec: 2100
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /about/health
```

Please point your websocket domain (ws.socialhour.vewmet.com) to your ingress public IP. Please check google cloud console to make sure this helm chart create 2 ingresses with 2 public IP.

_Originally posted by @minhpq331 in https://github.com/minhpq331/jitsi-scalable-helm/issues/1#issuecomment-988488361_

**Comment by minhpq331** [comment]
Did you apply my `BackendConfig` resource? To check if it has any effect go to Google Cloud Console > Load Balancer > LB detail, you should see timeout config like this:
![image](https://user-images.githubusercontent.com/16734662/145922704-f684b4b8-e8d3-417d-b7c0-8e9ffde7b077.png)

**Comment by bharath-naik** [comment]
hi @minhpq331 ... what i observed today all of sudden is, without the ```BackendConfig``` jitsi worked fine and i have connected to the room for more than 2 hrs and after applying the ```BackendConfig``` it is giving me the 502 response now. should i use this backend service or not.

![image](https://user-images.githubusercontent.com/20774548/145973422-83eca2b5-c6be-4bac-a385-62a73791d347.png)

here is the response.
![image](https://user-images.githubusercontent.com/20774548/145973764-2999a8f4-0010-4e71-94e2-dfd69f58e984.png)

steps to reproduce the issue.
1. installed the helm chart
2. > GCE backend config (kubectl apply this file)
3. changed the annotations at haproxy and jvb websocket and finally once again installed ```helm upgrade --install -f values-custom.yaml easyjitsi .``` [precisely 460 or 461 and 396 or 397](https://github.com/minhpq331/jitsi-scalable-helm/blob/main/values.yaml)
```
haproxy:
  enabled: true
  image: 
    repository: haproxy
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  podAnnotations: {}

  service:
    type: ClusterIP
    annotations: # changedhere
      beta.cloud.google.com/backend-config: '{"ports": {"80":"haproxy-config"}}'
    port: 80
    # nodePort: 32080

  # Expose this as your web domain
  ingress:
    enabled: true
-------------------------------------------------------------------------------------
 # Expose websocket
  websocket:
    service:
      enabled: true
      type: ClusterIP
      annotations: #changedhere
        beta.cloud.google.com/backend-config: '{"ports": {"9090":"jvb-websocket-config"}}'
      ports:
        http: 9090
        # admin: 8080

    # Enable this ingress to auto expose colibri websocket and load balance between jvbs
```

**Comment by minhpq331** [comment]
Oh, my bad, this backendconfig.yaml is configured for my other project, which uses different healthcheck method. Correct backendconfig is (change healthcheck port to haproxy port 80)

```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: haproxy-config
spec:
  timeoutSec: 2100 # timeout connection for haproxy, set your
  connectionDraining:
    drainingTimeoutSec: 2100
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: HTTP
    requestPath: /
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: jvb-websocket-config
spec:
  timeoutSec: 2100 # 35 minutes  # timeout connection for haproxy, set your
  connectionDraining:
    drainingTimeoutSec: 2100
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /about/health
```

FYI, remove backendconfig while using xmpp websocket cause your room disconnected after 30 seconds (Google LB timeout). You can remove backendconfig if you disable ws connection
