### ISSUE TITLE
Issue video with meet has more 2 participant

### ISSUE THREAD

**Issue by marcoadasilvaa** [minhpq331/jitsi-scalable-helm#5]
Hello!

thanx a lot for your contribution with this repo.

I have some issue when a install helm chart on GKE, I followed the steps described in the issues https://github.com/minhpq331/jitsi-scalable-helm/issues/1 https://github.com/minhpq331/jitsi-scalable-helm/issues/2 and solved some errors, but when the meet have 3 participant, video turn off.

![image](https://user-images.githubusercontent.com/4205973/153785329-26e4d397-8863-45a5-8a19-1f950b85fb73.png)

![image](https://user-images.githubusercontent.com/4205973/153785373-a7d58b52-a185-4ec5-88b0-7ffe03554a5a.png)

Relevanted error fron jvb pod
```
Feb 14, 2022 1:07:01 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: new Pair added: 10.124.0.6:30000/udp/host -> 192.168.100.6:61289/udp/host (stream-2692ff36.RTP).
Feb 14, 2022 1:07:01 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 10.124.0.6:30000/udp/host -> 192.168.100.6:61289/udp/host (stream-2692ff36.RTP)
```

My setup has the follow steps:

1 - Upgrade de version of image jitsi to: appVersion: "stable-6865"
2 - Set backend config whit 80 for haproxy and 9090 for jvm
3 - Ingress settings:
```
jvb:
  websocket:
    service:
      annotations: 
        beta.cloud.google.com/backend-config: '{"ports": {"9090":"jvb-websocket-config"}}'
    ingress:
      enabled: true
      className: ""
      annotations:
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.global-static-ip-name: xx.xx.xx.xx
        networking.gke.io/managed-certificates: managed-cert
      hosts:
        - ws.meet.jitsi.com

haproxy:
  service:
    annotations: 
      beta.cloud.google.com/backend-config: '{"ports": {"80":"haproxy-config"}}'
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.global-static-ip-name: xx.xx.xx.xx
      networking.gke.io/managed-certificates: managed-cert
    hosts:
      - host: meet.jitsi.com
        paths:
          - path: /*
            pathType: ImplementationSpecific
```
4 - Only one shard
5 - Some settings with k8s:

![image](https://user-images.githubusercontent.com/4205973/153785901-af689643-9281-4251-8f2f-5517991f4b18.png)

I suspect that it may be a problem with udp 30000, but I wanted to check if I am ignoring any configuration.

Thanx in advanced
